default:
  image: docker:25.0.3-dind
  before_script:
    - dockerd -l fatal &
    - sleep 5
  tags:
    - amd64-runner

variables:
  KUBERNETES_CPU_REQUEST: 60
  KUBERNETES_MEMORY_REQUEST: 256G
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 500G

build:
  stage: build

  before_script:
    - apk add --update curl && apk add --update git unzip zip && rm -rf /var/cache/apk/*
    - dockerd -l fatal &
    # - docker login -u "$ART_DOCKER_USER" -p "$ART_DOCKER_PASS" $ART_DOCKER_REG
    # Installing JFrog CLI
    - curl -fL https://install-cli.jfrog.io | sh
    - chmod +x /usr/local/bin/jf
    # Configure Artifactory instance with JFrog CLI
    - pwd
    - projFolder=$(pwd)
    # - cd /usr/local/bin/
    - /usr/local/bin/jf --version
    - /usr/local/bin/jf c add artifactory-server --url=$ART_PLAT_URL --user=$ART_PLAT_USER --password=$ART_PLAT_PASS
    - /usr/local/bin/jf rt ping


  script:
    # Variables
    - QCOM_RELEASE=qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-2.0.1
    - DOCKER_TAG="qcom-6.6.90-qli.1.5-ver.1.1_qim-product-sdk-2.0.1_20.04"
    - URL="https://github.com/qualcomm-linux/qcom-manifest"
    - BRANCH="qcom-linux-scarthgap"
    - MANIFEST_FILE="${QCOM_RELEASE}.xml"
    - MACHINE="qcs8275-iq-8275-evk"
    - ARCH="arm"
    - DISTRO="qcom-wayland"
    - IMAGE="qcom-multimedia-image"
    - USER=lnxbuild
    - UID=2366345
    - GID=2366345
    - WORK_DIR="/home/${USER}/app"

    # Docker Build & Run
    - docker build --build-arg USER=${USER} --build-arg UID=${UID} --build-arg GID=${GID} --no-cache -t ${DOCKER_TAG} .
    #- docker run --name build ${DOCKER_TAG} -u ${URL} -b ${BRANCH} -m ${MANIFEST_FILE} -M ${MACHINE} -d ${DISTRO} -i ${IMAGE} -w "${WORK_DIR}/${DOCKER_TAG}" -a ${ARCH}
    #- mkdir -p /target/qcs8275-iq-8275-evk/qcom-multimedia-image
    #- mkdir -p /target/qcs8275-iq-8275-evk/sdk
    #- mkdir -p /target/qcs8275-iq-8275-evk/qim_prod_sdk_artifacts
    #- docker cp build:${WORK_DIR}/qcom-6.6.90-qli.1.5-ver.1.1_qim-product-sdk-2.0.1_20.04/build-qcom-wayland/tmp-glibc/deploy/images/qcs8275-iq-8275-evk/qcom-multimedia-image/. /target/qcs8275-iq-8275-evk/qcom-multimedia-image/
    #- docker cp build:${WORK_DIR}/qcom-6.6.90-qli.1.5-ver.1.1_qim-product-sdk-2.0.1_20.04/build-qcom-wayland/tmp-glibc/deploy/sdk/. /target/qcs8275-iq-8275-evk/sdk/
    #- docker cp build:${WORK_DIR}/qcom-6.6.90-qli.1.5-ver.1.1_qim-product-sdk-2.0.1_20.04/build-qcom-wayland/tmp-glibc/deploy/qim_prod_sdk_artifacts/. /target/qcs8275-iq-8275-evk/qim_prod_sdk_artifacts/
    #- docker cp build:${WORK_DIR}/qcom-6.6.90-qli.1.5-ver.1.1_qim-product-sdk-2.0.1_20.04/NOTICE /target/qcs8275-iq-8275-evk/
    #- docker cp build:${WORK_DIR}/qcom-6.6.90-qli.1.5-ver.1.1_qim-product-sdk-2.0.1_20.04/NO.LOGIN.BINARY.LICENSE.QTI.pdf /target/qcs8275-iq-8275-evk/
    #- zip -r arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-2.0.1.zip /target/qcs8275-iq-8275-evk
    #- zip -r arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-image-2.0.1.zip /target/qcs8275-iq-8275-evk/qcom-multimedia-image /target/qcs8275-iq-8275-evk/NOTICE /target/qcs8275-iq-8275-evk/NO.LOGIN.BINARY.LICENSE.QTI.pdf
    #- zip -r arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-artifacts-2.0.1.zip /target/qcs8275-iq-8275-evk/qim_prod_sdk_artifacts /target/qcs8275-iq-8275-evk/NOTICE /target/qcs8275-iq-8275-evk/NO.LOGIN.BINARY.LICENSE.QTI.pdf
    #- zip -r arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-esdk-2.0.1.zip /target/qcs8275-iq-8275-evk /target/qcs8275-iq-8275-evk/sdk -i /target/qcs8275-iq-8275-evk/sdk/*-toolchain-ext-*.sh -i /target/qcs8275-iq-8275-evk/NOTICE -i /target/qcs8275-iq-8275-evk/NO.LOGIN.BINARY.LICENSE.QTI.pdf
    #- zip -r arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-standardsdk-2.0.1.zip /target/qcs8275-iq-8275-evk /target/qcs8275-iq-8275-evk/sdk -i /target/qcs8275-iq-8275-evk/sdk/*-toolchain-*.sh -x /target/qcs8275-iq-8275-evk/sdk/*-toolchain-ext-*.sh -i /target/qcs8275-iq-8275-evk/NOTICE -i /target/qcs8275-iq-8275-evk/NO.LOGIN.BINARY.LICENSE.QTI.pdf
    - wget https://artifacts.codelinaro.org/artifactory/qli-ci/flashable-binaries/qimpsdk/qcs8275-iq-8275-evk/arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-image-2.0.1.zip
    - unzip arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-image-2.0.1.zip
    - rm -rf arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-image-2.0.1.zip
    - wget https://artifacts.codelinaro.org/artifactory/qli-ci/flashable-binaries/qimpsdk/qcs8275-iq-8275-evk/arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-artifacts-2.0.1.zip
    - unzip -o arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-artifacts-2.0.1.zip
    - rm -rf arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-artifacts-2.0.1.zip
    - wget https://artifacts.codelinaro.org/artifactory/qli-ci/flashable-binaries/qimpsdk/qcs8275-iq-8275-evk/arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-standardsdk-2.0.1.zip
    - unzip -o arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-standardsdk-2.0.1.zip
    - rm -rf arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-standardsdk-2.0.1.zip
    - wget https://artifacts.codelinaro.org/artifactory/qli-ci/flashable-binaries/qimpsdk/qcs8275-iq-8275-evk/arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-esdk-2.0.1.zip
    - unzip -o arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-esdk-2.0.1.zip
    - rm -rf arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-esdk-2.0.1.zip
    - tree target
    #- docker rm build
    - zip -r arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-2.0.1.zip target/qcs8275-iq-8275-evk
    - /usr/local/bin/jf rt ping
    - /usr/local/bin/jf rt u --detailed-summary --flat=false --recursive arm-qcom-6.6.90-QLI.1.5-Ver.1.1_qim-product-sdk-2.0.1.zip qli-ci/flashable-binaries/qimpsdk/qcs8275-iq-8275-evk/