default:
  image: docker:25.0.3-dind
  before_script:
    - dockerd -l fatal &
    - sleep 5
  tags:
    - arm64-runner

variables:
  KUBERNETES_CPU_REQUEST: 32
  KUBERNETES_MEMORY_REQUEST: 128G
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 200G

build:
  stage: build

  before_script:
    - apk add --update curl && apk add --update git unzip zip && rm -rf /var/cache/apk/*
    - dockerd -l fatal &
    # - docker login -u "$ART_DOCKER_USER" -p "$ART_DOCKER_PASS" $ART_DOCKER_REG
    # Installing JFrog CLI
    - curl -fL https://install-cli.jfrog.io | sh
    - chmod +x /usr/local/bin/jf
    # Configure Artifactory instance with JFrog CLI
    - pwd
    - projFolder=$(pwd)
    # - cd /usr/local/bin/
    - /usr/local/bin/jf --version
    - /usr/local/bin/jf c add artifactory-server --url=$ART_PLAT_URL --user=$ART_PLAT_USER --password=$ART_PLAT_PASS
    - /usr/local/bin/jf rt ping

  script:
    # Variables
    - QCOM_RELEASE=qcom-6.6.28-QLI.1.1-Ver.1.0_qim-product-sdk-1.1.1
    - DOCKER_TAG="qcom-6.6.28-qli.1.1-ver.1.0_qim-product-sdk-1.1.1_20.04"
    - URL="https://github.com/quic-yocto/qcom-manifest"
    - BRANCH="qcom-linux-kirkstone"
    - MANIFEST_FILE="${QCOM_RELEASE}.xml"
    - MACHINE="qcm6490"
    - DISTRO="qcom-wayland"
    - IMAGE="qcom-multimedia-image"
    - USER=lnxbuild
    - UID=2366345
    - GID=2366345
    - WORK_DIR="/home/${USER}/app"

    # Docker Build & Run
    - docker build --build-arg USER=${USER} --build-arg UID=${UID} --build-arg GID=${GID} --no-cache -t ${DOCKER_TAG} .
    - docker run --name build ${DOCKER_TAG} -u ${URL} -b ${BRANCH} -m ${MANIFEST_FILE} -M ${MACHINE} -d ${DISTRO} -i ${IMAGE} -w "${WORK_DIR}/${DOCKER_TAG}"
    - mkdir -p /target/qcm6490/qcom-multimedia-image
    - mkdir -p /target/qcm6490/sdk
    - mkdir -p /target/qcm6490/qim_prod_sdk_artifacts
    - docker cp build:${WORK_DIR}/qcom-6.6.28-qli.1.1-ver.1.0_qim-product-sdk-1.1.1_20.04/build-qcom-wayland/tmp-glibc/deploy/images/qcm6490/qcom-multimedia-image/. /target/qcm6490/qcom-multimedia-image/
    - docker cp build:${WORK_DIR}/qcom-6.6.28-qli.1.1-ver.1.0_qim-product-sdk-1.1.1_20.04/build-qcom-wayland/tmp-glibc/deploy/sdk/. /target/qcm6490/sdk/
    - docker cp build:${WORK_DIR}/qcom-6.6.28-qli.1.1-ver.1.0_qim-product-sdk-1.1.1_20.04/build-qcom-wayland/tmp-glibc/deploy/qim_prod_sdk_artifacts/. /target/qcm6490/qim_prod_sdk_artifacts/
    - docker cp build:${WORK_DIR}/qcom-6.6.28-qli.1.1-ver.1.0_qim-product-sdk-1.1.1_20.04/NOTICE /target/qcm6490/
    - docker cp build:${WORK_DIR}/qcom-6.6.28-qli.1.1-ver.1.0_qim-product-sdk-1.1.1_20.04/NO.LOGIN.BINARY.LICENSE.QTI.pdf /target/qcm6490/
    - zip -r qcom-6.6.28-QLI.1.1-Ver.1.0_qim-product-sdk-1.1.1.zip /target/qcm6490
    - docker rm build
    - /usr/local/bin/jf rt ping
    - /usr/local/bin/jf rt u --detailed-summary --flat=false --recursive qcom-6.6.28-QLI.1.1-Ver.1.0_qim-product-sdk-1.1.1.zip qli-ci/flashable-binaries/qimsdk/qcm6490/arm/

    
